### PR TITLE
Add php linting via travis

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by cagabi** [comment]
Hi Reedy, thanks for this.
What is the aim in the of the linter in the travis build?

**Comment by reedy** [comment]
Making sure people don't commit invalid PHP? :)

**Comment by cagabi** [comment]
Ok, great!

**Comment by reedy** [comment]
I'm a little confused... Closed but not merged? :)

**Comment by cagabi** [comment]
Sorry about that

**Comment by reedy** [comment]
heh, thanks!

**Pull request merged**
